# Generated by Django 4.2 on 2023-10-31 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_rankinglibro_libro_rankings'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrosFavoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'Deseando Leer'), ('2', 'Leido')], default='1', max_length=1)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Libro Favorito de Usuario',
                'verbose_name_plural': 'Libros Favoritos de Usuarios',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='libros_favoritos',
            field=models.ManyToManyField(through='users.LibrosFavoritos', to='biblioteca.libro'),
        ),
    ]
